weather_in_id:
  path: /weather/id/{location}
  controller: App\Controller\WeatherController:idAction
  requirements:
    id: \d+

weather_in_city:
  path: /weather/city/{city}
  controller: App\Controller\WeatherController:cityAction